name: Build and Release VantaSafe

on:
  push:
    tags:
      - 'v*'  # Runs when a tag like v1.0.0 is pushed

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publish App (Single EXE)
        run: dotnet publish "./Vanta Safe/Vanta Safe.csproj" -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Vanta Safe/bin/Release/net8.0-windows/win-x64/publish/Vanta Safe.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}